export const ActionTypes = {
  SET_SESSION_STATUS: 'SET_SESSION_STATUS',
  SET_FAIL_TYPE: 'SET_FAIL_TYPE',
  SET_FAIL_REASON: 'SET_FAIL_REASON',
  SET_INVITE_LINK: 'SET_INVITE_LINK',

  SHOW_DIALOG: 'SHOW_DIALOG',
  TYPING_MESSAGE: 'TYPING_MESSAGE',
  PEER_IS_TYPING: 'PEER_IS_TYPING',

  ADD_CONNECTION_MESSAGE: 'ADD_CONNECTION_MESSAGE',
  INCOMING_TEXT: 'INCOMING_TEXT',
  INCOMING_FILE: 'INCOMING_FILE',
  SEND_TEXT: 'SEND_TEXT',
  SEND_FILE: 'SEND_FILE',
  TRANSFER_UPDATE: 'TRANSFER_UPDATE',
  TRANSFER_DONE: 'TRANSFER_DONE',
  TRANSFER_BLOB: 'TRANSFER_BLOB',
};

export const Stages = {
  INITIAL: 'INITIAL',
  SELF_ID: 'SELF_ID',
  HANDSHAKE: 'HANDSHAKE',
  CONNECTED: 'CONNECTED',
  FAILED: 'FAILED',
  DISCONNECTED: 'DISCONNECTED',
};

export const MessageSources = {
  CONNECTION: 'CONNECTION',
  INCOMING: 'INCOMING',
  OUTGOING: 'OUTGOING',
};
