export const ActionTypes = {
  SET_SESSION_STATUS: 'SET_SESSION_STATUS',
  SET_FAIL_TYPE: 'SET_FAIL_TYPE',
  SET_FAIL_REASON: 'SET_FAIL_REASON',
  SET_INVITE_LINK: 'SET_INVITE_LINK',

  SHOW_DIALOG: 'SHOW_DIALOG',

  INCOMING_TEXT: 'INCOMING_TEXT',
  INCOMING_FILE: 'INCOMING_FILE',
  SEND_TEXT: 'SEND_TEXT',
  SEND_FILE: 'SEND_FILE',
  TRANSFER_UPDATE: 'TRANSFER_UPDATE',
  TRANSFER_DONE: 'TRANSFER_DONE',
  TRANSFER_BLOB: 'TRANSFER_BLOB',
};

export const Stages = {
  INITIAL: 'INITIAL',
  SELF_ID: 'SELF_ID',
  HANDSHAKE: 'HANDSHAKE',
  CONNECTED: 'CONNECTED',
  FAILED: 'FAILED',
  DISCONNECTED: 'DISCONNECTED',
};
